using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Text;
using NPOI.XWPF.UserModel; // NPOI Core

namespace AutoSopCreator
{
    public class ExportService
    {
        private const long CompressionQuality = 70L; 

        public void ExportToHtml(List<StepModel> steps, string filePath)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html><head><meta charset='utf-8'>");
            sb.AppendLine("<title>自動化 SOP 文件</title>");
            sb.AppendLine("<style>");
            sb.AppendLine("body { font-family: 'Microsoft JhengHei', sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background: #f9f9f9; }");
            sb.AppendLine(".header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 10px; }");
            sb.AppendLine(".step-card { background: white; border: 1px solid #ddd; padding: 20px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }");
            sb.AppendLine(".step-title { font-size: 1.2em; color: #0078d4; font-weight: bold; margin-bottom: 10px; }");
            sb.AppendLine(".step-desc { font-size: 1.1em; margin-bottom: 15px; color: #333; }");
            sb.AppendLine(".step-img { max-width: 100%; border: 1px solid #ccc; display: block; margin: 0 auto; }");
            sb.AppendLine(".footer { text-align: center; color: #888; margin-top: 40px; font-size: 0.9em; }");
            sb.AppendLine("</style></head><body>");
            sb.AppendLine("<div class='header'><h1>軟體操作標準作業程序 (SOP)</h1><p>Generated by Cool Idea AI</p></div>");

            foreach (var step in steps)
            {
                sb.AppendLine("<div class='step-card'>");
                sb.AppendLine($"<div class='step-title'>步驟 {step.StepNumber}</div>");
                sb.AppendLine($"<p class='step-desc'>{step.Description}</p>");
                string imgBase64 = ImageHelper.ToBase64(step.Screenshot, CompressionQuality);
                sb.AppendLine($"<img class='step-img' src='data:image/jpeg;base64,{imgBase64}' />");
                sb.AppendLine("</div>");
            }
            sb.AppendLine("<div class='footer'><p>本文件由 AI Scribe 自動生成</p></div>");
            sb.AppendLine("</body></html>");
            File.WriteAllText(filePath, sb.ToString());
        }

        public void ExportToWord(List<StepModel> steps, string filePath)
        {
            // 使用 NPOI 建立 Word
            XWPFDocument doc = new XWPFDocument();

            // 1. 大標題
            var titlePara = doc.CreateParagraph();
            titlePara.Alignment = ParagraphAlignment.CENTER;
            var titleRun = titlePara.CreateRun();
            titleRun.SetText("軟體操作標準作業程序 (SOP)");
            titleRun.IsBold = true;
            titleRun.FontSize = 20;

            // 2. 日期
            var datePara = doc.CreateParagraph();
            datePara.Alignment = ParagraphAlignment.CENTER;
            var dateRun = datePara.CreateRun();
            dateRun.SetText($"生成日期: {DateTime.Now:yyyy-MM-dd HH:mm}");
            dateRun.FontSize = 10;
            datePara.SpacingAfter = 400; // twips

            foreach (var step in steps)
            {
                // 3. 步驟標題
                var stepPara = doc.CreateParagraph();
                var stepRun = stepPara.CreateRun();
                stepRun.SetText($"步驟 {step.StepNumber}");
                stepRun.IsBold = true;
                stepRun.FontSize = 14;
                stepRun.SetColor("00008B"); // DarkBlue

                // 4. 說明文字
                var descPara = doc.CreateParagraph();
                descPara.SpacingAfter = 200;
                var descRun = descPara.CreateRun();
                descRun.SetText(step.Description);
                descRun.FontSize = 12;

                // 5. 插入圖片
                using (MemoryStream ms = ImageHelper.ToCompressedStream(step.Screenshot, CompressionQuality))
                {
                    var imgPara = doc.CreateParagraph();
                    imgPara.Alignment = ParagraphAlignment.CENTER;
                    var imgRun = imgPara.CreateRun();

                    // NPOI 圖片單位換算 (EMU)
                    int width = 500;
                    double ratio = (double)step.Screenshot.Height / step.Screenshot.Width;
                    int height = (int)(width * ratio);

                    imgRun.AddPicture(ms, (int)PictureType.JPEG, $"step_{step.StepNumber}.jpg", width * 9525, height * 9525);
                }

                // 6. 分隔線 (NPOI: Border Bottom)
                var divPara = doc.CreateParagraph();
                divPara.SpacingBefore = 200;
                divPara.SpacingAfter = 400;
                // 設定下底線
                divPara.BorderBottom = Borders.Single;
                //divPara.BorderBottomSize = 6;
                // 注意：NPOI 的顏色設定可能因版本有異，這裡使用標準屬性
            }

            using (var fs = new FileStream(filePath, FileMode.Create, FileAccess.Write))
            {
                doc.Write(fs);
            }
        }
    }
}